name: Test cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - name: Docker images
        run: docker image ls

      - name: build project
        container:
          image: python:3.9
          volumes:
            - .:/srv
        run: ls -la

      - name: Docker images
        run: docker image ls
