name: Test cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker

    steps:
      - uses: actions/checkout@v2

      - name: Docker images
        run: docker image ls

      - name: My first step
        uses: docker://alpine:3.8

      - name: Docker images
        run: docker image ls
